// Generated by CoffeeScript 1.7.1
var ATEM, ATEM_ADDR, ATEM_PORT, sw;

ATEM = require('./atem.coffee');

ATEM_ADDR = process.env['ATEM_ADDR'] || '172.16.0.2';

ATEM_PORT = process.env['ATEM_PORT'] || 9910;

sw = new ATEM;

sw.connect(ATEM_ADDR, ATEM_PORT);
